name: Docker Image CI publish

on:
  push:
    tags:
      - 'v*'

env:
  images_list: |
    vreitech/docker-ldc
    ghcr.io/${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Fillup metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.images_list }}
        flavor: |
          latest=auto
        tags: |
          type=schedule
          type=semver,pattern={{version}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: ./Containerfile
        plarforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
